version: '3'

services:
  websocket:
    build: .
    depends_on: 
      - mongodbhost
    environment:
      - dbURL=mongodb://mongodbhost:27017/websocket
      - SECRET=se3cret334
    ports:
      - "8080:8080"

  static-server:
    build: public
    ports:
      - "443:443"
      - "80:80"

  mongodbhost:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        command: mongod --logpath=/dev/null # --quiet